### ISSUE TITLE
GraphiQL - Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by nadavten** [apollographql/apollo-server#502]
![image](https://user-images.githubusercontent.com/17804204/29233779-9a6f702c-7efb-11e7-90db-ad56356ebaf4.png)

"apollo-server-express": "^1.1.0",
    "body-parser": "^1.17.2",
    "express": "^4.15.4",
    "graphql": "^0.10.5",
    "graphql-tools": "^1.1.0"

my code:
```
import * as express from 'express';
import * as bodyParser from 'body-parser';
import {graphqlExpress,graphiqlExpress} from 'apollo-server-express';
import schema from './schema';

const app = express();
app.use('/graphql',bodyParser.json(),graphqlExpress({schema}));

app.use('/graphiql',graphiqlExpress({
    endpointURL:'/graphql'
}));

const PORT = 3000;
app.listen(PORT,()=>{
    console.log(`running on port ${PORT}`);
});
```

**Comment by duvet86** [comment]
Same here.
The issue happens because of react-dom stored in https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js
There's a ret at the end of the file.
Apollo graphiql pulls react-dom from there.
Have a look at apollo-server-module-graphiql, renderGraphiQL.js

**Comment by nadavten** [comment]
i dont understand. the problem ia at the cdn file? or the apollo file?

**Comment by nadavten** [comment]
problem is with latest chrome version (60.0.3112.90 (Official Build) (64-bit)). something with service workers.
edge works fine

**Comment by duvet86** [comment]
Does graphiql use a service worker? 
The issue is on the cdn. Open it, scroll to the end, there's a "ret" breaking the script.

**Comment by nadavten** [comment]
works fine on edge browser

**Comment by beornborn** [comment]
same issue, agree with @duvet86 

workaround:
change `react-dom@15.6.1/dist/react-dom.min.js to react-dom@15.6.0/dist/react-dom.min.js` in 
`node_modules/apollo-server-module-graphiql/renderGraphiQL.js` and restart server.

**Comment by ferrugemjs** [comment]
> same issue, agree with @duvet86

workaround:
change react-dom@15.6.1/dist/react-dom.min.js to react-dom@15.6.0/dist/react-dom.min.js in
node_modules/apollo-server-module-graphiql/dist/renderGraphiQL.js and restart server.

**Comment by nadavten** [comment]
@ferrugemjs didnt work for me

**Comment by nadavten** [comment]
maybe the 3rd party packages should be stored within the package itself

**Comment by stubailo** [comment]
I think this was an issue with the CDN that's resolved now? Either way #376 is the right solution, looking forward to a PR there!

**Comment by OriginalEXE** [comment]
I am still having this issue, unfortunately :( Looking forward to the #376 solution :)

**Comment by matt-w** [comment]
Was having the same issue on localhost and found that it was related to the Fair AdBlocker Chrome extension. Whitelisting localhost solved the issue for me.
